[book]
authors = ["victor.houisse"]
language = "en"
src = "src"
title = "Distributed Mesh Adapatation"


[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
smart-punctuation = true
mathjax-support = true
static-assets = ["images"]
