# Workflow pour construire et déployer un site mdBook sur GitHub Pages
# Ce workflow s'exécute à chaque push sur la branche 'main'.

name: Déploiement mdBook sur Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.40 # Version de mdBook stable
    steps:
      - uses: actions/checkout@v4

      - name: Installer mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf -y | sh
          rustup update
          cargo install --version ${MDBOOK_VERSION} mdbook

      - name: Configuration de GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Construction du livre avec mdBook
        run: mdbook build

      - name: Télécharger l'artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './book'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4